name: Nightly Releases
on:
  schedule:
    - cron: "3 0 * * *"

jobs:
  main:
    permissions:
      packages: write
      contents: write
    uses: ./.github/workflows/release.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      branch: "main"
      nightly: true
  v7_0:
    permissions:
      packages: write
      contents: write
    uses: ./.github/workflows/release.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      branch: "7.0"
      nightly: true
